server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/accentureTest?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 853988127
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: DateSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 5000ms       #连接超时时间
    lettuce:
      pool:
        max-active: 8     #Redis连接池最大连接数（负数表示没有限制）
        max-wait: -1ms    #Redis连接池最大阻塞等待时间
        max-idle: 8       #Redis连接池最大空闲连接数
        min-idle: 0       #Redis连接池最小空闲连接数


mybatis:
  type-aliases-package: com.accenture.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
